### ISSUE TITLE
.gitignore is not ignored with --skip-substr

### ISSUE THREAD

**Issue by alexdevteam** [karnkaul/locc#20]
In an empty folder, with a single file called `.gitignore`, using the command `./locc.exe --skip-substr=.gitignore .` does not ignore the file:
![image](https://user-images.githubusercontent.com/16354904/130287512-7a62b958-6018-45a1-82fd-02768a151f07.png)

**Comment by karnkaul** [comment]
Thanks for the bug report @alexdevteam! Should be fixed in [v0.1.1](https://github.com/karnkaul/locc/releases/tag/v0.1.1).
